// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// find_two_places
LogicalVector find_two_places(IntegerVector id, NumericVector lon, NumericVector lat, float dis_thres);
RcppExport SEXP lawsonLoc_find_two_places(SEXP idSEXP, SEXP lonSEXP, SEXP latSEXP, SEXP dis_thresSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< IntegerVector >::type id(idSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type lon(lonSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type lat(latSEXP );
        Rcpp::traits::input_parameter< float >::type dis_thres(dis_thresSEXP );
        LogicalVector __result = find_two_places(id, lon, lat, dis_thres);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// handle_loc
DataFrame handle_loc(IntegerVector id, NumericVector lon, NumericVector lat, IntegerVector time, IntegerVector worktime);
RcppExport SEXP lawsonLoc_handle_loc(SEXP idSEXP, SEXP lonSEXP, SEXP latSEXP, SEXP timeSEXP, SEXP worktimeSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< IntegerVector >::type id(idSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type lon(lonSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type lat(latSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type time(timeSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type worktime(worktimeSEXP );
        DataFrame __result = handle_loc(id, lon, lat, time, worktime);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// splitPath
IntegerVector splitPath(IntegerVector time);
RcppExport SEXP lawsonLoc_splitPath(SEXP timeSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< IntegerVector >::type time(timeSEXP );
        IntegerVector __result = splitPath(time);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
