# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

findTwoPlaces <- function(loc, dis_thres) {
    .Call('lawsonLoc_findTwoPlaces', PACKAGE = 'lawsonLoc', loc, dis_thres)
}

handle_loc <- function(data) {
    .Call('lawsonLoc_handle_loc', PACKAGE = 'lawsonLoc', data)
}

rcpp_hello_world <- function() {
    .Call('lawsonLoc_rcpp_hello_world', PACKAGE = 'lawsonLoc')
}

splitPath <- function(time) {
    .Call('lawsonLoc_splitPath', PACKAGE = 'lawsonLoc', time)
}

