# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_two_places <- function(id, lon, lat, dis_thres) {
    .Call('lawsonLoc_find_two_places', PACKAGE = 'lawsonLoc', id, lon, lat, dis_thres)
}

handle_loc <- function(id, lon, lat, time, worktime) {
    .Call('lawsonLoc_handle_loc', PACKAGE = 'lawsonLoc', id, lon, lat, time, worktime)
}

splitPath <- function(time) {
    .Call('lawsonLoc_splitPath', PACKAGE = 'lawsonLoc', time)
}

